name: rw_base
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #框架
  #https://pub.dev/packages/logger
  logger: 1.1.0
  #https://pub.dev/packages/image (手写签名 - 转图片)
  image: 3.2.0
  #https://pub.flutter-io.cn/packages/intl
  intl: 0.17.0
  #https://pub.dev/packages/timezone
  timezone: 0.8.0

  #原生插件
  #https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: 6.0.17
  #https://pub.flutter-io.cn/packages/video_compress
  video_compress: 3.1.1
  #https://pub.flutter-io.cn/packages/device_info_plus
  device_info_plus: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500

flutter_intl:
  enabled: true